language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t mimattos/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mimattos/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "sa-east-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-sa-east-1-552561319578"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $aws_access_key
  secret_access_key: $aws_secret_key